from enum import Enum

class DiscordChannel(str, Enum):
    TEXT_TO_SPEECH = 'TEXT_TO_SPEECH'
    YESTERDAY_TOP_GAINER_SCRAPER_HISTORY = 'YESTERDAY_TOP_GAINER_SCRAPER_HISTORY'
    CHATBOT_ERROR_LOG = 'CHATBOT_ERROR_LOG'
    
    
    