from enum import Enum

class OracleQuery(str, Enum):
    ADD_TOP_GAINER_QUERY = "INSERT INTO TOP_GAINER_HISTORY (TICKER, COMPANY, SECTOR, INDUSTRY, SCAN_DATE, PRICE, VOLUME, PERCENTAGE, MARKET_CAP, COUNTRY) VALUES (:1, :2, :3, :4, :5, :6, :7, :8, :9, :10)"
    DELETE_ALL_TOP_GAINER_QUERY = "DELETE FROM TOP_GAINER_HISTORY"
    GET_TOP_GAINER_QUERY = 'SELECT * FROM TOP_GAINER_HISTORY WHERE PERCENTAGE >= :percentage AND SCAN_DATE BETWEEN :start_date AND :end_date'
    COUNT_TOP_GAINER_TICKER_QUERY = "SELECT COUNT(*) FROM TOP_GAINER_HISTORY WHERE TICKER = :ticker AND TRUNC(SCAN_DATE, 'DD') = TRUNC(:scan_date, 'DD')"