-- Create common user (which has the same identity across all containers)
CREATE USER C##demo IDENTIFIED BY demo
DEFAULT TABLESPACE USERS;

grant dba to C##demo;


--------------------------------------------------------
--  DDL for Table TOP_GAINER_HISTORY
--------------------------------------------------------
  CREATE TABLE "TOP_GAINER_HISTORY" 
   (	"TICKER" VARCHAR2(4 BYTE), 
	"COMPANY" VARCHAR2(200 BYTE), 
	"SECTOR" VARCHAR2(100 BYTE), 
	"INDUSTRY" VARCHAR2(100 BYTE), 
	"SCAN_DATE" TIMESTAMP (6), 
	"PRICE" FLOAT(126), 
	"VOLUME" NUMBER, 
	"PERCENTAGE" FLOAT(126), 
	"MARKET_CAP" NUMBER, 
	"COUNTRY" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table TOP_GAINER_HISTORY
--------------------------------------------------------

  ALTER TABLE "TOP_GAINER_HISTORY" MODIFY ("TICKER" NOT NULL ENABLE);
  ALTER TABLE "TOP_GAINER_HISTORY" MODIFY ("COMPANY" NOT NULL ENABLE);
  ALTER TABLE "TOP_GAINER_HISTORY" MODIFY ("SCAN_DATE" NOT NULL ENABLE);
  ALTER TABLE "TOP_GAINER_HISTORY" MODIFY ("PRICE" NOT NULL ENABLE);
  ALTER TABLE "TOP_GAINER_HISTORY" MODIFY ("VOLUME" NOT NULL ENABLE);
  ALTER TABLE "TOP_GAINER_HISTORY" MODIFY ("PERCENTAGE" NOT NULL ENABLE);

